# Generated by Django 3.2.8 on 2021-10-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllergySymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ColdSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name= 'MuscleSysmptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FlatulenceSysmptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DiarrheaSysmptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ConstipationSysmptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AllergiccontactSysmptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UrticariaSysmptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AllergicweatherSysmptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ColdallergySysmptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AccidentSysmptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ParasiteSysmptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CoughSysmptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
